/*
 * The MIT License
 *
 * Copyright 2016 jeferson.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.ufba.dcc.mata62.ufbaboards.boards;

import javax.swing.JLabel;

/**
 *
 * @author jeferson
 */
public class BoardLabelsVertical extends javax.swing.JPanel {

    /**
     * Creates new form BoardLabelsVertical
     * @param labels
     */
    public BoardLabelsVertical(String[] labels) {
        initComponents();
        
        /* Tamanho horizontal é o tamanho total dividido pela quantidade de elementos */
        int verticalLength   = 432 / labels.length;
        int horizontalLength = 20;
        
        /* Aux JLabel */
        JLabel auxLabel;
        
        for(String label : labels){
            /* Create an aux label*/
            auxLabel = new JLabel();
            
            /* Configurate the label */
            auxLabel.setFont(new java.awt.Font("Dialog", 1, 18));
            auxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            auxLabel.setText(label);
            auxLabel.setPreferredSize(new java.awt.Dimension(horizontalLength, verticalLength));
            
            /* Add label */
            add(auxLabel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(20, 432));
        setMinimumSize(new java.awt.Dimension(20, 432));
        setPreferredSize(new java.awt.Dimension(20, 432));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
