/*
 * The MIT License
 *
 * Copyright 2016 jeferson.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.ufba.dcc.mata62.ufbaboards.gui;

import javax.swing.JPanel;

/**
 *
 * @author jeferson
 */
public class TwoPlayersStartPanel extends javax.swing.JPanel {

    private final JPanel appPanel;
    
    /**
     * Creates new form UfbaBoardPanel
     * @param gameName
     * @param newAppPanel
     */
    public TwoPlayersStartPanel(String gameName, JPanel newAppPanel) {
        initComponents();
        
        /* Set Game Name */
        gameNameLabel.setText(gameName);
        
        /* Save App Panel */
        appPanel = newAppPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presentationLogoLabel = new javax.swing.JLabel();
        apresentationLabel = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player1Input = new javax.swing.JTextField();
        player2Label = new javax.swing.JLabel();
        player2Input = new javax.swing.JTextField();
        gameNameLabel = new javax.swing.JLabel();
        startGameButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(660, 480));
        setMinimumSize(new java.awt.Dimension(660, 480));
        setPreferredSize(new java.awt.Dimension(660, 480));

        presentationLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufba/dcc/mata62/ufbaboards/resources/ufba_boards_logo.png"))); // NOI18N
        presentationLogoLabel.setToolTipText("UFBABoard Logo");

        apresentationLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        apresentationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apresentationLabel.setText("A platform for board games");

        player1Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1Label.setText("Player 1");
        player1Label.setToolTipText("Player 1");
        player1Label.setMaximumSize(new java.awt.Dimension(100, 30));
        player1Label.setMinimumSize(new java.awt.Dimension(100, 30));
        player1Label.setPreferredSize(new java.awt.Dimension(100, 30));

        player1Input.setToolTipText("Player1 Name");

        player2Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2Label.setText("Player 2");
        player2Label.setToolTipText("Player 2");
        player2Label.setMaximumSize(new java.awt.Dimension(100, 30));
        player2Label.setMinimumSize(new java.awt.Dimension(100, 30));
        player2Label.setPreferredSize(new java.awt.Dimension(100, 30));

        player2Input.setToolTipText("Player2 Name");

        gameNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gameNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameNameLabel.setToolTipText("Game Name");

        startGameButton.setMnemonic('t');
        startGameButton.setText("Start Game");
        startGameButton.setToolTipText("Start the specified game");
        startGameButton.setMaximumSize(new java.awt.Dimension(200, 34));
        startGameButton.setMinimumSize(new java.awt.Dimension(200, 34));
        startGameButton.setPreferredSize(new java.awt.Dimension(200, 34));
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1Input)
                            .addComponent(player2Input)))
                    .addComponent(apresentationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presentationLogoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(presentationLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apresentationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("UFBABoardPanel");
        getAccessibleContext().setAccessibleDescription("UFBABoard default panel");
    }// </editor-fold>//GEN-END:initComponents

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startGameButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apresentationLabel;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JTextField player1Input;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player2Input;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel presentationLogoLabel;
    private javax.swing.JToggleButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
