/*
 * The MIT License
 *
 * Copyright 2016 jeferson.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.ufba.dcc.mata62.ufbaboards.gui;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jeferson
 */
public abstract class UfbaBoardFrame extends javax.swing.JFrame {
    /* Some constants */
    public static final String GAMEHELPMENU = "gamehelp_item";
    public static final String UNDOMENU = "undo_item";
    public static final String REDOMENU = "redo_item";
    public static final String NEWGAMEMENU = "newgame_item";
    public static final String NEWSPECIALMENU = "newspecial_item";
    public static final String CHANGEPLAYERMENU = "changeplayer_item";
    public static final String STATISTICSMENU = "statistics_item";
    public static final String RESTARTMENU = "restartgame_item";
    
    /* Attributes */
    private String gameName;
    public static final String VERSION = "1.0";
    
    /**
     * Creates new form UfbaBoardFrame
     */
    public UfbaBoardFrame() {
        /* Init Components */
        initComponents();
        
        gameName = "";
    }
    
    public void addNewGamePanel(JPanel newGamePanel, String gamePanelName){
        /* Get App Panel*/
        CardLayout appPanelLayout = (CardLayout) appPanel.getLayout();
        
        /* Add a Entry Panel*/
        appPanel.add(newGamePanel, gamePanelName);
        
        /* Show Entry Panel */
        appPanelLayout.show(appPanel, gamePanelName);
    }
    
    protected abstract void gameHelpMenuAction();
    protected abstract void undoItemAction();
    protected abstract void redoItemAction();
    protected abstract void newGameMenuAction();
    protected abstract void newSpecialGameAction();
    protected abstract void changePlayersMenuAction();
    protected abstract void statisticsMenuAction();
    protected abstract void restartGameMenuAction();
        
    public void setGameName(String gameName){
        this.gameName = gameName;
    }
    
    public void changeMenuState(String item, boolean state){
        switch(item){
            case GAMEHELPMENU:
                gameHelpMenuItem.setEnabled(state);
                break;
            case UNDOMENU:
                gameHelpMenuItem.setEnabled(state);
                break;
            case REDOMENU:
                redoMenuItem.setEnabled(state);
                break;
            case NEWGAMEMENU:
                newGameMenuItem.setEnabled(state);
                break;
            case NEWSPECIALMENU:
                newSpecialGameMenuItem.setEnabled(state);
                break;
            case CHANGEPLAYERMENU:
                changePlayersMenuItem.setEnabled(state);
                break;
            case STATISTICSMENU:
                statisticsMenuItem.setEnabled(state);
                break;
            case RESTARTMENU:
                restartGameMenuItem.setEnabled(state);
                break;
        }
    }
    
    public void enableMenuState(String item){
        changeMenuState(item, true);
    }
    
    public void disableMenuState(String item){
        changeMenuState(item, false);
    }
    
    public void enableMultipleItens(String[] itens){
        for(String item : itens)
            changeMenuState(item, true);
    }

    public void disableMultipleItens(String[] itens){
        for(String item : itens)
            changeMenuState(item, false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appPanel = new javax.swing.JPanel();
        gamePanel1 = new br.ufba.dcc.mata62.ufbaboards.gui.GamePanel();
        appMenu = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        newSpecialGameMenuItem = new javax.swing.JMenuItem();
        gameMenuExtra = new javax.swing.JMenu();
        separatorGame1 = new javax.swing.JPopupMenu.Separator();
        restartGameMenuItem = new javax.swing.JMenuItem();
        saveGameMenuItem = new javax.swing.JMenuItem();
        separatorGame2 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        optionsSeparator = new javax.swing.JPopupMenu.Separator();
        statisticsMenuItem = new javax.swing.JMenuItem();
        changePlayersMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        gameHelpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UFBA Boards");
        setIconImage(new ImageIcon(this.getClass().getResource("/br/ufba/dcc/mata62/ufbaboards/resources/ufba_icon.png")).getImage());
        setMaximumSize(new java.awt.Dimension(660, 501));
        setMinimumSize(new java.awt.Dimension(660, 501));
        setName("MainFrame"); // NOI18N
        setResizable(false);

        appPanel.setToolTipText("");
        appPanel.setMaximumSize(new java.awt.Dimension(660, 480));
        appPanel.setMinimumSize(new java.awt.Dimension(660, 480));
        appPanel.setName("appPanel"); // NOI18N
        appPanel.setVerifyInputWhenFocusTarget(false);
        appPanel.setLayout(new java.awt.CardLayout());
        appPanel.add(gamePanel1, "gamePanel");

        appMenu.setToolTipText("UFBABoards Menu");
        appMenu.setMaximumSize(new java.awt.Dimension(76, 1024));

        gameMenu.setMnemonic('G');
        gameMenu.setText("Game");
        gameMenu.setToolTipText("Game Menu");

        newGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newGameMenuItem.setMnemonic('N');
        newGameMenuItem.setText("New Game");
        newGameMenuItem.setToolTipText("New Standard Game");
        newGameMenuItem.setEnabled(false);
        newGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(newGameMenuItem);

        newSpecialGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        newSpecialGameMenuItem.setMnemonic('w');
        newSpecialGameMenuItem.setText("New Special Game");
        newSpecialGameMenuItem.setToolTipText("New Special Game");
        newSpecialGameMenuItem.setEnabled(false);
        newSpecialGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSpecialGameMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(newSpecialGameMenuItem);

        gameMenuExtra.setMnemonic('m');
        gameMenuExtra.setText("Game Menu");
        gameMenuExtra.setToolTipText("Extra Game Menu");
        gameMenuExtra.setEnabled(false);
        gameMenu.add(gameMenuExtra);
        gameMenu.add(separatorGame1);

        restartGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        restartGameMenuItem.setMnemonic('R');
        restartGameMenuItem.setText("Restart Game");
        restartGameMenuItem.setToolTipText("Restart the current game");
        restartGameMenuItem.setEnabled(false);
        restartGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartGameMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(restartGameMenuItem);

        saveGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveGameMenuItem.setMnemonic('S');
        saveGameMenuItem.setText("Save Game");
        saveGameMenuItem.setToolTipText("Save Current Game");
        saveGameMenuItem.setEnabled(false);
        gameMenu.add(saveGameMenuItem);
        gameMenu.add(separatorGame2);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit Game");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(exitMenuItem);

        appMenu.add(gameMenu);

        optionsMenu.setMnemonic('O');
        optionsMenu.setText("Options");
        optionsMenu.setToolTipText("Game Options Menu");

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setMnemonic('U');
        undoMenuItem.setText("Undo");
        undoMenuItem.setToolTipText("Undo last movement");
        undoMenuItem.setEnabled(false);
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setMnemonic('R');
        redoMenuItem.setText("Redo");
        redoMenuItem.setToolTipText("Redo last movement");
        redoMenuItem.setEnabled(false);
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(redoMenuItem);
        optionsMenu.add(optionsSeparator);

        statisticsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        statisticsMenuItem.setMnemonic('t');
        statisticsMenuItem.setText("Statistics");
        statisticsMenuItem.setToolTipText("Statistics of the current game");
        statisticsMenuItem.setEnabled(false);
        statisticsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(statisticsMenuItem);

        changePlayersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        changePlayersMenuItem.setMnemonic('p');
        changePlayersMenuItem.setText("Change Players");
        changePlayersMenuItem.setToolTipText("Change Players Name");
        changePlayersMenuItem.setEnabled(false);
        changePlayersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePlayersMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(changePlayersMenuItem);

        appMenu.add(optionsMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        helpMenu.setToolTipText("Game Help");

        gameHelpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        gameHelpMenuItem.setMnemonic('e');
        gameHelpMenuItem.setText("Game Help");
        gameHelpMenuItem.setToolTipText("Game Help");
        gameHelpMenuItem.setEnabled(false);
        gameHelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameHelpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(gameHelpMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.setToolTipText("About this game");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        appMenu.add(helpMenu);

        setJMenuBar(appMenu);
        appMenu.getAccessibleContext().setAccessibleName("UFBABoards Menu");
        appMenu.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        this.setLocationRelativeTo(null);
        appPanel.getAccessibleContext().setAccessibleName("App Main Panel");
        appPanel.getAccessibleContext().setAccessibleDescription("App Main Panel");

        getAccessibleContext().setAccessibleDescription("UFBA Boards Main Frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(  this,
                                        "<html> "
                                            + "<center>"
                                                + "<h1> UFBA Boards V " + VERSION + "</h1>"
                                                + "<p></p>"
                                                + "<p>UFBA Boards is a creation of Jeferson Lima</p>"
                                                + "<p>a Computer Science student at UFBA.</p>"
                                                + "<p>UFBA Boards is released under the MIT LICENSE.</p>"
                                                + "<p></p><p></p>"
                                                + "<b> Copyright 2016 Jeferson Lima. </b>"
                                            + "</center>"
                                        + "</html>",
                                        "About UFBA Boards - " + gameName,
                                        JOptionPane.DEFAULT_OPTION,
                                        new ImageIcon(this.getClass().getResource("/br/ufba/dcc/mata62/ufbaboards/resources/ufba_icon.png")));
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void gameHelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameHelpMenuItemActionPerformed
        gameHelpMenuAction();
    }//GEN-LAST:event_gameHelpMenuItemActionPerformed

    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
        undoItemAction();
    }//GEN-LAST:event_undoMenuItemActionPerformed

    private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
        redoItemAction();
    }//GEN-LAST:event_redoMenuItemActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
        newGameMenuAction();
    }//GEN-LAST:event_newGameMenuItemActionPerformed

    private void newSpecialGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSpecialGameMenuItemActionPerformed
        newSpecialGameAction();
    }//GEN-LAST:event_newSpecialGameMenuItemActionPerformed

    private void changePlayersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePlayersMenuItemActionPerformed
        changePlayersMenuAction();
    }//GEN-LAST:event_changePlayersMenuItemActionPerformed

    private void statisticsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsMenuItemActionPerformed
        statisticsMenuAction();
    }//GEN-LAST:event_statisticsMenuItemActionPerformed

    private void restartGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartGameMenuItemActionPerformed
        restartGameMenuAction();
    }//GEN-LAST:event_restartGameMenuItemActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuBar appMenu;
    protected javax.swing.JPanel appPanel;
    private javax.swing.JMenuItem changePlayersMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem gameHelpMenuItem;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenu gameMenuExtra;
    protected br.ufba.dcc.mata62.ufbaboards.gui.GamePanel gamePanel1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JMenuItem newSpecialGameMenuItem;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JPopupMenu.Separator optionsSeparator;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem restartGameMenuItem;
    private javax.swing.JMenuItem saveGameMenuItem;
    private javax.swing.JPopupMenu.Separator separatorGame1;
    private javax.swing.JPopupMenu.Separator separatorGame2;
    private javax.swing.JMenuItem statisticsMenuItem;
    private javax.swing.JMenuItem undoMenuItem;
    // End of variables declaration//GEN-END:variables
}
